config/routes.rb
BnuojV4::Application.routes.draw do

  
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do
    root :to => 'home#index'
    post 'users/login' => 'users#login'
    get 'users/logout' => 'users#logout'
    get 'statuses/compile_info/:id' => 'statuses#compile_info'
    get 'signin' => 'users#signin'

    get 'server_time' => 'home#server_time'

    resources :statuses
    resources :news
    resources :messages
    resources :contests
    resources :problems
    resources :users
    get 'users/compare/:user1/:user2' => 'users#compare', as: 'user_compare'
  end

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  self.table_name = "contest"
  self.primary_key = "cid"
  self.inheritance_column = :_type_disabled

  has_many :runs, class_name: "Status", primary_key: "cid",
      foreign_key: "contest_belong", inverse_of: :contest
  has_many :replay_runs, class_name: "ReplayStatus", primary_key: "cid",
      foreign_key: "contest_belong", inverse_of: :contest
  has_many :clarifies, class_name: "ContestClarify", primary_key: "cid",
      foreign_key: "cid", inverse_of: :contest
  has_many :problem_infos, class_name: "ContestProblem", primary_key: "cid",
      foreign_key: "cid", inverse_of: :contest
  has_many :challenges, primary_key: "cid", foreign_key: "cid",
      inverse_of: :contest

  scope :standard, -> { where(isvirtual: 0)}
  scope :virtual, -> { where(isvirtual: 1)}
  scope :scheduled, -> { where('start_time > NOW()')}
  scope :running, -> { where('
      start_time < NOW() AND (
        end_time > NOW() OR
        (
          has_cha = 1 AND
          challenge_end_time > NOW()
        )
      )
  ') }

  # Real contest end time for each type of contest.
  def final_time
    return challenge_end_time if has_cha
    return end_time
  end

  # Whether is in challenging phase, always false for non challenge contest.
  def challenging?
    return false unless has_cha
    return Time.now > challenge_start_time && Time.now < challenge_end_time
  end

  # Whether is in coding phase, or running for non challenge contest.
  def coding?
    return Time.now > start_time && Time.now < end_time
  end

  # Whether is in intermission phase, always false for non challenge contest.
  def intermission?
    return false unless has_cha
    return Time.now > end_time && Time.now < challenge_start_time
  end

  # Whether contest has started.
  def started?
    return Time.now > start_time
  end

  # Whether contest is running.
  def running?
    return Time.now > start_time && Time.now < final_time
  end

  # Whether contest has finished.
  def ended?
    return Time.now > final_time
  end

  # Status display text for datatables.
  # TODO(51isoft): I18n.
  def status_text
    return "Running" if running?
    return "Scheduled" if !started?
    return "Passed" if ended?
  end

  # Access text for datatables.
  # TODO(51isoft): I18n.
  def access_text
    case isprivate
    when 1
      "Private"
    when 2
      "Password"
    else
      "Public"
    end
  end

  # Formats start time for datatables.
  def start_time_display
    start_time.strftime OJ_CONFIG["misc"]["datetime_format"]
  end

  # Formats end time for datatables.
  def final_time_display
    final_time.strftime OJ_CONFIG["misc"]["datetime_format"]
  end

  # Whether username is in this contest.
  def has_user username
    case isprivate
    when 1
      !ContestUser.where(username: username, cid: cid).empty?
    when 2
      # TODO: Password type
      false
    else
      true
    end
  end

end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController

  def index
    @page_title = t("contest.titles.list");
    respond_to do |format|
      format.html
      format.json {
        render json: ContestsDatatable.new(view_context)
      }
    end
  end

  def show
  end

end

app/views/contests/_form.html.erb
<%= form_for(@contest) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1><%= t "contest.titles.edit" %></h1>

<%= render 'form' %>

<%= link_to t("global.links.show"), @contest %> |
<%= link_to t("global.links.back"), contests_path %>

app/views/contests/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <% if logged_in? %>
      <button id="arrangevirtual" class="btn btn-primary">
        <%= t "contest.btns.arrange_vcontest" %>
      </button>
    <% end %>
    <div class="btn-group virtual-btns">
      <button class="btn btn-default" is-virtual=""><%= t "contest.btns.all" %></button>
      <button class="btn btn-default" is-virtual="0"><%= t "contest.btns.standard" %></button>
      <button class="btn btn-default" is-virtual="1"><%= t "contest.btns.virtual" %></button>
    </div>
    <div class="btn-group type-btns">
      <button class="btn btn-default" contest-type="all"><%= t "contest.btns.all" %></button>
      <button class="btn btn-default" contest-type="0"><%= t "contest.btns.icpc" %></button>
      <button class="btn btn-default" contest-type="1"><%= t "contest.btns.cf" %></button>
      <button class="btn btn-default" contest-type="99"><%= t "contest.btns.replay" %></button>
      <button class="btn btn-default" contest-type="-99"><%= t "contest.btns.non_replay" %></button>
    </div>
    <div class="btn-group access-btns">
      <button class="btn btn-default" access=""><%= t "contest.btns.all" %></button>
      <button class="btn btn-default" access="0"><%= t "contest.btns.public" %></button>
      <button class="btn btn-default" access="1"><%= t "contest.btns.private" %></button>
      <button class="btn btn-default" access="2"><%= t "contest.btns.password" %></button>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <table class="table table-hover table-striped" id="contestlist">
      <thead>
        <tr>
          <th> <%= t "contest.headers.cid" %> </th>
          <th width="30%"> <%= t "contest.headers.title" %> </th>
          <th> <%= t "contest.headers.start_time" %> </th>
          <th> <%= t "contest.headers.end_time" %> </th>
          <th> <%= t "contest.headers.status" %> </th>
          <th> <%= t "contest.headers.access" %> </th>
          <th> <%= t "contest.headers.manager" %> </th>
          <th> <%= t "contest.headers.private" %> </th>
          <th> <%= t "contest.headers.type" %> </th>
        </tr>
      </thead>
      <tbody>
      </tbody>
      <tfoot>
      </tfoot>
    </table>
  </div>
</div>

app/views/contests/new.html.erb
<h1><%= t "contest.titles.new" %></h1>

<%= render 'form' %>

<%= link_to t("global.links.back"), contests_path %>

app/views/contests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to t("global.links.edit"), edit_contest_path(@contest) %> |
<%= link_to t("global.links.back"), contests_path %>