config/routes.rb
BnuojV4::Application.routes.draw do

  
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do
    root :to => 'home#index'
    post 'users/login' => 'users#login'
    get 'users/logout' => 'users#logout'
    get 'statuses/compile_info/:id' => 'statuses#compile_info'
    get 'signin' => 'users#signin'

    get 'server_time' => 'home#server_time'

    resources :statuses
    resources :news
    resources :messages
    resources :contests
    resources :problems
    resources :users
    get 'users/compare/:user1/:user2' => 'users#compare', as: 'user_compare'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  self.table_name = "user"
  self.primary_key = "uid"

  has_many :runs, class_name: "Status", primary_key: "username",
      foreign_key: "username", inverse_of: :user
  has_many :in_messages, class_name: "Message", primary_key: "username",
      foreign_key: "reciever", inverse_of: :receiver
  has_many :out_messages, class_name: "Message", primary_key: "username",
      foreign_key: "sender", inverse_of: :sender
  has_many :clarifies, class_name: "ContestClarify", primary_key: "username",
      foreign_key: "username", inverse_of: :questioner
  has_many :tags, primary_key: "username", foreign_key: "username",
      inverse_of: :user
  has_many :privileges, inverse_of: :user

  # Override to specify the columns to show.
  def to_json(options = {})
    if options[:except].nil?
      options[:except] = []
    end
    options[:except] |= [:password, :photo, :total_value, :lock_status, :isroot]
    super(options)
  end

  # Admin check
  def is_admin?
    isroot == 1
  end

  def is_owner_of? contest
    contest.owner == name
  end

  def unread_message_count
    in_messages.where(status: 0).count
  end

  # Whether user accepted pid
  def is_problem_accepted? pid
    runs.where(result: "Accepted", pid: pid).count > 0
  end

  # Whether user submitted pid
  def is_problem_submitted? pid
    runs.where(pid: pid).count > 0
  end

  # Whether user has certain privilege
  def can? (privilege, restriction = {"any" => "any"})
    is_admin? ||
        privileges.where(
            privilege: privilege,
            restrict_to_key: restriction.keys[0],
            restrict_to_value: restriction.values[0]).count > 0
  end

  # Calculate the rank of user
  def rank
    User.where('local_ac > :local_ac OR
        ( local_ac = :local_ac AND ( total_ac > :total_ac OR
        ( total_ac = :total_ac AND ( total_submit < :total_submit OR
        ( total_submit = :total_submit AND username < :username )))))',
        local_ac: local_ac, total_ac: total_ac, total_submit: total_submit,
            username: username).count + 1
  end

  # Return an array of accepted problems' id
  def accepted_pids
    Status.where( username: username, result: 'Accepted' ).select(:pid).
        distinct.order(:pid).map(&:pid)
  end

  # Return an array of submitted problems' id
  def submitted_pids
    Status.where( username: username ).select(:pid).
        distinct.order(:pid).map(&:pid)
  end

  # Return an array of tried but failed problems' id
  def failed_pids
    submitted_pids - accepted_pids
  end

  # User statistics
  def stat
    counts = runs.normal.group("result").count
    counts["Other"] = total_submit - counts.map{|k,v| v}.reduce(:+)
    return counts
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  rescue_from UserError::UserNotFound do
    @error_msg = t "user.prompts.nonexist"
    respond_to do |format|
      format.html { render "home/error" }
      format.json { render json: { msg: @error_msg }, status: :bad_request }
    end
  end

  def login
    password = hash_password(params[:password])
    user = User.find_by(username: params[:username])
    if user.nil? || user.password != password
      render(
          json: { msg: t("user.prompts.userpass_error") },
          status: :not_acceptable)
      return
    end
    cookie_time = 0
    if !params[:cksave].nil?
      cookie_time = 3.years
    end
    set_cookie("username", user.username, cookie_time)
    set_cookie("password", encrypt_password(user.password), cookie_time)
    respond_to do |format|
      format.html { redirect_to params[:referer] } if params[:referer]
      format.html { redirect_to controller: "home", action: "index" }
      format.json { render json: { msg: t("user.prompts.logged_in") } }
    end
  end

  def signin
    respond_to do |format|
      format.html
    end
  end

  def logout
    set_cookie("username", "")
    set_cookie("password", "")
    redirect_to :back
  end

  # GET /users
  # GET /users.json
  def index
    # @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by(username: params[:id])
    raise UserError::UserNotFound if @user.nil?
    options = {}
    options[:except] = []
    if !logged_in? || !current_user.is_admin?
      options[:except] |= [:ipaddr]
    end
    respond_to do |format|
      format.html
      format.json { render json: @user.to_json(options) }
    end
  end

  # GET /users/compare/username1/username2
  def compare
    @user1 = User.find_by(username: params[:user1])
    @user2 = User.find_by(username: params[:user2])
    raise UserError::UserNotFound if @user1.nil? || @user2.nil?
    respond_to do |format|
      format.html
      format.json { render json: {
          'only_user1_solved' => @user1.accepted_pids - @user2.accepted_pids,
          'only_user2_solved' => @user2.accepted_pids - @user1.accepted_pids,
          'both_solved' => @user1.accepted_pids & @user2.accepted_pids,
          'user1_failed' => @user1.failed_pids,
          'user2_failed' => @user2.failed_pids,
          'both_failed' => @user1.failed_pids & @user2.failed_pids
      }}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def user_params
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def before_login_prompt
    if params[:referer]
      "<p class=\"alert alert-info\">#{t "global.prompts.need_login"}</p>".html_safe 
    end
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= t "user.titles.edit" %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1><%= t "user.titles.list" %></h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to t("global.links.show"), user %></td>
        <td><%= link_to t("global.links.edit"), edit_user_path(user) %></td>
        <td><%= link_to t("global.links.delete"), user, method: :delete, data: { confirm: t("global.prompts.is_sure") } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("global.links.new"), new_user_path %>

app/views/users/new.html.erb
<h1><%= t "user.titles.new" %></h1>

<%= render 'form' %>

<%= link_to t("global.links.back"), users_path %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <h2><%= t 'user.show.info_of', user: @user.username %></h2>
    <table class="table" id="userinfo">
      <tr>
        <th class="col-md-3"><%= t 'user.username' %></th>
        <td class="col-md-9"><%= @user.username %></td>
      </tr>
      <tr><th><%= t 'user.id' %></th><td><%= @user.id %></td></tr>
      <tr><th><%= t 'user.rank' %></th><td><%= @user.rank %></td></tr>
      <tr><th><%= t 'user.nickname' %></th><td><%= @user.nickname %></td></tr>
      <tr><th><%= t 'user.school' %></th><td><%= @user.school %></td></tr>
      <tr><th><%= t 'user.email' %></th><td><%= @user.email %></td></tr>
      <tr>
        <th><%= t 'user.register_time' %></th>
        <td><%= l @user.register_time, format: :long %></td>
      </tr>
      <tr>
        <th><%= t 'user.last_login' %></th>
        <td><%= l @user.last_login_time, format: :long %></td>
      </tr>
<% if logged_in? && current_user.is_admin? %>
      <tr><th><%= t 'user.last_login_ip' %></th><td><%= @user.ipaddr %></td></tr>
<% end %>
      <tr>
        <th><%= t 'status.results.accepted' %></th>
        <td>
          <%= @user.total_ac %>
          <button id="showac" class="btn btn-primary btn-xs" data-toggle="collapse"
              data-target="#userac" aria-controls="userac" aria-expanded="false">
            <%= t "global.btns.show_hide" %>
          </button>
          <div style="width:100%" id="userac" class="collapse">
            <%= raw @user.accepted_pids.map{ |pid| link_to pid, problem_path, id: pid }
                .join('&nbsp; ') %>
          </div>
        </td>
      </tr>
      <tr>
        <th><%= t 'user.show.compare' %></th>
        <td class="form-inline">
          <form class="form-inline" id="compare">
            <div class="input-group input-group-sm col-md-6">
              <input class="form-control" type="text" id="compare_with" 
                  value="<%= logged_in? ? current_user.username : "" %>" />
              <span class="input-group-btn">
                <button type="submit" class="btn btn-primary"><%= t "user.show.do_compare" %>
                </button>
              </span>
            </div>
            <button id="hide_compare" type="button" class="btn btn-primary btn-sm">
              <%= t "global.links.hide" %>
            </button>
          </form>
        </div>
        <div class="collapse" id="compare_info"></div>
        </td>
      </tr>
    </table>
  </div>
  <div class="col-md-4 well">
    <div id="user_stat_pie"></div>
    <table id="user_stat" class="table">
      <tr>
        <th class="col-md-9"><%= t 'user.total_submit' %></th>
        <td class="col-md-3">
          <%= link_to @user.total_submit, statuses_path( user: @user.username ) %>
        </td>
      </tr>
<% @user.stat.each do |result, count| %>
      <tr>
        <th><%= result %></th>
  <% if result == "Other" %>
        <td><%= count %></td>
  <% else %>
        <td><%= link_to count, statuses_path( user: @user.username, result: result ) %></td>
  <% end %>
      </tr>
<% end %>
    </table>
  </div>
</div>

app/views/users/signin.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= t "user.titles.signin" %></h1>
    <%= before_login_prompt %>
    <form method="POST" action="<%= url_for :controller => 'users', :action => 'login' %>"
        accept-charset="UTF-8" id="login_form" class="ajform form-horizontal" role="form">
      <div class="form-group">
        <label for="username" class="control-label col-sm-3"><%= t "user.username" %></label>
        <div class="col-sm-9">
          <input class="form-control" name="username" type="text" value="" id="username">
        </div>
      </div>
      <div class="form-group">
        <label for="password" class="control-label col-sm-3"><%= t "user.password" %></label>
        <div class="col-sm-9">
          <input class="form-control" name="password" type="password" value="" id="password">
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
          <div class="checkbox">
            <label>
              <input name="cksave" type="checkbox" value="1"> <%= t "user.signin.remeber_me" %>
            </label>
          </div>
        </div>
      </div>
      <div class="text-right">
        <span id="msgbox" style="display:none"></span>
        <input class="btn btn-primary" type="submit" value="Login">
        <a class='btn btn-default' id="register-btn" href="#"><%= t "global.links.register" %></a>
      </div>
    </form>
  </div>
</div>