config/routes.rb
BnuojV4::Application.routes.draw do

  
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do
    root :to => 'home#index'
    post 'users/login' => 'users#login'
    get 'users/logout' => 'users#logout'
    get 'statuses/compile_info/:id' => 'statuses#compile_info'
    get 'signin' => 'users#signin'

    get 'server_time' => 'home#server_time'

    resources :statuses
    resources :news
    resources :messages
    resources :contests
    resources :problems
    resources :users
    get 'users/compare/:user1/:user2' => 'users#compare', as: 'user_compare'
  end

end

app/models/news.rb
class News < ActiveRecord::Base
  self.table_name = "news"
  self.primary_key = "newsid"

  def time_added_display
    time_added.strftime OJ_CONFIG["misc"]["datetime_format"]
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  # GET /news/{:id}
  def show
    news = News.find(params[:id]);
    if news.nil?
      render json: { msg: t("news.prompts.nonexist") }, status: :not_found
      return
    end
    render json: news.to_json(:methods => [:time_added_display])
  end

end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1><%= t "news.titles.edit" %></h1>

<%= render 'form' %>

<%= link_to t("global.links.show"), @news %> |
<%= link_to t("global.links.back"), news_index_path %>

app/views/news/index.html.erb
<h1><%= t "news.titles.list" %></h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= link_to t("global.links.show"), news %></td>
        <td><%= link_to t("global.links.edit"), edit_news_path(news) %></td>
        <td><%= link_to t("global.links.delete"), news, method: :delete, data: { confirm: t("global.prompts.is_sure") } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("global.links.new"), new_news_path %>

app/views/news/new.html.erb
<h1><%= t "news.titles.new" %></h1>

<%= render 'form' %>

<%= link_to t("global.links.back"), news_index_path %>